server:
    port: 8087
spring:
    application:
        name: notification-service
    boot:
        admin:
            client:
                url: http://localhost:8084

logging:
    level:
        org:
            springframework:
                boot:
                    cloud:
                        gateway: trace
                        gateway.route.RouteDefinitionLocator: info
        root: info

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
        fetch-registry: 'true'
    instance:
        preferIpAddress: true
        instance-id: ${spring.application.name}:${random.uuid}

management:
    endpoints:
        web:
            exposure:
                include: '*'
        enabled-by-default: 'true'
    endpoint:
        configprops:
            enabled: 'true'
        beans:
            enabled: 'true'
        health:
            show-details: always
        shutdown:
            enabled: 'true'

