eureka:
    instance:
        instance-id: ${spring.application.name}:${random.uuid}
    client:
        fetch-registry: true
        instance:
            preferIpAddress: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
management:
    endpoint:
        beans:
            enabled: true
        configprops:
            enabled: true
        health:
            show-details: always
        shutdown:
            enabled: true
    endpoints:
        enabled-by-default: true
        web:
            exposure:
                include: '*'
server:
    port: 8084
spring:
    application:
        name: admin-server
